name: Trigger auto deployment for pcdalanapi

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ master ]
    paths:
    - '**'
    - '.github/workflows/pcdalanapi-AutoDeployTrigger-14518246-8088-4ee1-940b-bd33796119b4.yml'

  # Allow mannually trigger 
  workflow_dispatch:      

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: gadacr.azurecr.io
          username: ${{ secrets.PCDALANAPI_REGISTRY_USERNAME }}
          password: ${{ secrets.PCDALANAPI_REGISTRY_PASSWORD }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: gadacr.azurecr.io/alanapi:${{ github.sha }}
          file: ./Dockerfile
          context: ./


  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.PCDALANAPI_AZURE_CREDENTIALS }}


      - name: Deploy to containerapp
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az config set extension.use_dynamic_install=yes_without_prompt
            az containerapp registry set -n pcdalanapi -g Demo_PCDContainerApp --server gadacr.azurecr.io --username  ${{ secrets.PCDALANAPI_REGISTRY_USERNAME }} --password ${{ secrets.PCDALANAPI_REGISTRY_PASSWORD }}
            az containerapp update -n pcdalanapi -g Demo_PCDContainerApp --image gadacr.azurecr.io/alanapi:${{ github.sha }}
